books/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^create_cat/$', views.create_cat, name='create_cat'),
    # url(r'^info_book/$', views.info_book, name='info_book'),
    # url(r'^books/$', views.books, name='books'),
    # url(r'^authors/$', views.authors, name='authors'),
    # url(r'^category/$', views.category, name='category'),
    ##url(r'^books/$', views.BookListView.as_view(), name='books'),
    # url(r'^detail_books/$', views.BookDetailView.as_view(), name='detail_books'),
    #     url(r'category/add/$', views.CategoryCreateView.as_view(), name='category_add'),
    url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'^categories/$', views.CategoryListView.as_view(), name='categories'),
    url(r'^all_books/$', views.BookListView.as_view(), name='all_books'),

    url(r'^detail_book/(?P<pk>\d)/$', views.BookDetailView.as_view(), name='detail_book'),
    url(r'^detail_author/(?P<pk>\d)/$', views.AuthorDetailView.as_view(), name='detail_author'),
    url(r'^detail_category/(?P<pk>\d)/$', views.CategoryDetailView.as_view(), name='detail_category'),

    url(r'^category_update/(?P<pk>\d)/$', views.CategoryUpdate.as_view(), name='category_update'),
    url(r'^book_update/(?P<pk>\d)/$', views.BookUpdate.as_view(), name='book_update'),
    url(r'^author_update/(?P<pk>\d)/$', views.AuthorUpdate.as_view(), name='author_update'),

    url(r'^category_delete/(?P<pk>\d)/$', views.CategoryDelete.as_view(), name='category_delete'),
    url(r'^book_delete/(?P<pk>\d)/$', views.BookDelete.as_view(), name='book_delete'),
    url(r'^author_delete/(?P<pk>\d)/$', views.AuthorDelete.as_view(), name='author_delete'),

    url(r'^category_create/$', views.CategoryFormView.as_view(), name='category_create'),
    url(r'^book_create/$', views.BookFormView.as_view(), name='book_create'),
    url(r'^author_create/$', views.AuthorFormView.as_view(), name='author_create'),
    url(r'^comment_create/$', views.CommentFormView.as_view(), name='comment_create'),

    url(r'^set_like/$', views.set_like, name='set_like'),
    url(r'^set_dislike/$', views.set_dislike, name='set_dislike'),

]

library/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
    url(r'^my_auth/', include('my_auth.urls', namespace="my_auth")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_auth/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login_view$', views.login_view, name='login_view'),
    url(r'^register_view/$', views.UserFormView.as_view(), name='register_view'),
    ]

books/models.py
from django.db import models
from datetime import datetime


class Book(models.Model):
    title = models.CharField(max_length=30)
    year = models.DateField()
    description = models.CharField(max_length=1000)
    authors = models.ManyToManyField('Author')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='all_img', blank=True)
    prev = models.ImageField(upload_to='all_img', blank=True)

    # comment = models.ForeignKey('Comment', on_delete=models.CASCADE, blank=True, default=0)
    # rating = models.OneToOneField('Rating', on_delete=models.CASCADE, blank=True, default=0)
    def __str__(self):
        return '{0}'.format(self.title)


class Rating(models.Model):
    like = models.IntegerField()
    dislike = models.IntegerField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE)


class Comment(models.Model):
    comment = models.CharField(max_length=1000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)


class Category(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return '{0}'.format(self.title)


class Author(models.Model):
    name = models.CharField(max_length=30)
    date_bir = models.DateField()
    bio = models.CharField(max_length=1000)

    def __str__(self):
        return '{0}'.format(self.name)
        # return '{0} {1}'.format(self.authors, self.category)

books/forms.py
from django import forms
from .models import Book, Category, Author, Comment


class CategoryForm(forms.ModelForm):
    # name = forms.CharField(help_text="this is name")
    # name = forms.CharField(max_length=10)

    class Meta:
        model = Category
        fields = '__all__'


class AuthorForm(forms.ModelForm):
    # name = forms.CharField(help_text="this is name")
    # name = forms.CharField(max_length=10)

    class Meta:
        model = Author
        fields = '__all__'


class BookForm(forms.ModelForm):
    # name = forms.CharField(help_text="this is name")
    # name = forms.CharField(max_length=10)

    class Meta:
        model = Book
        fields = '__all__'


class CommentForm(forms.ModelForm):
    # name = forms.CharField(help_text="this is name")
    # name = forms.CharField(max_length=10)

    class Meta:
        model = Comment
        fields = '__all__'

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import ModelFormMixin

from .models import Book, Category, Author, Comment, Rating
from django.template import loader
from django.views.generic import View, ListView, CreateView, DetailView, FormView, UpdateView, DeleteView
from django.utils import timezone
from .forms import CategoryForm, AuthorForm, BookForm,  CommentForm
from django.urls import reverse_lazy
import json


def index(request):
    # return HttpResponse("Hello, world!")
    books = Book.objects.all()
    for b in books:
        id = b.id
        print(id)
        get_r = Rating.objects.filter(book_id=id).exists()
        print(get_r)

        if get_r == False:
            Rating.objects.create(like=0, dislike=0, book_id=id)

    return render(request, 'books/index.html',
                  {'books': books})


# list view --------------------------------------------------
class CategoryListView(ListView):
    template_name = 'books/category_list.html'
    model = Category
    context_object_name = 'categories'


class AuthorListView(ListView):
    template_name = 'books/authors_list.html'
    model = Author
    context_object_name = 'authors'


class BookListView(ListView):
    template_name = 'books/books_list.html'
    model = Book
    context_object_name = 'all_books'
# end list view --------------------------------------------------


# delete --------------------------------------------------
class BookDelete(DeleteView):
    model = Book
    fields = ['title']
    template_name = 'books/book_confirm_delete.html'
    # success_url = reverse_lazy('/books/category/')
    success_url = '/books/all_books/'


class CategoryDelete(DeleteView):
    model = Category
    fields = ['title']
    template_name = 'books/category_confirm_delete.html'
    # success_url = reverse_lazy('/books/category/')
    success_url = '/books/categories/'


class AuthorDelete(DeleteView):
    model = Author
    fields = ['name']
    template_name = 'books/author_confirm_delete.html'
    # success_url = reverse_lazy('/books/category/')
    success_url = '/books/authors/'
# end delete --------------------------------------------------


# detail view --------------------------------------------------
class BookDetailView(DetailView):
    template_name = 'books/book_detail.html'
    '''
    model = Book
    context_object_name = 'books'
    pk_url_kwarg = 'pk'''
    model = Book
    # slug_url_kwarg = 'slug'
    # pk_url_kwarg = 'category_id'

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class AuthorDetailView(DetailView):
    template_name = 'books/author_detail.html'
    model = Author

    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class CategoryDetailView(DetailView):
    template_name = 'books/category_detail.html'
    model = Category

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
# end detail view --------------------------------------------------


# create view ??--------------------------------------------------
class CategoryCreateView(ListView):
    model = Category
    fields = ['title']
# ---------------------------------


# create view --------------------------------------------------
class CategoryFormView(CreateView):
    form_class = CategoryForm
    template_name = 'books/category_form.html'
    success_url = '/books/categories/'


class BookFormView(CreateView):
    form_class = BookForm
    template_name = 'books/book_form.html'
    success_url = '/books/all_books/'


class AuthorFormView(CreateView):
    form_class = AuthorForm
    template_name = 'books/author_form.html'
    success_url = '/books/authors/'


class CommentFormView(CreateView):
    form_class = CommentForm
    template_name = 'books/comment_form.html'
    success_url = '/'
# end create view --------------------------------------------------


# update view --------------------------------------------------
class CategoryUpdate(UpdateView):
    model = Category
    fields = '__all__'
    # template_name_suffix = '_update_form'
    template_name = 'books/category_update_form.html'
    success_url = '/books/categories/'


class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    # template_name_suffix = '_update_form'
    template_name = 'books/book_update_form.html'
    success_url = '/books/all_books/'


class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__'
    # template_name_suffix = '_update_form'
    template_name = 'books/author_update_form.html'
    success_url = '/books/authors/'
# end update view --------------------------------------------------

# -----------------------------------------------------------------------------------------


def set_like(request):
    id = request.GET.get('id', None)
    print(id)
    old_like = Rating.objects.get(book_id=id)
    old_like_value = old_like.like
    new_like = int(old_like_value) + 1
    Rating.objects.filter(book_id=id).update(like=new_like)
    return HttpResponse(json.dumps(str(new_like)))


def set_dislike(request):
    id = request.GET.get('id', None)
    print(id)
    old_dislike = Rating.objects.get(book_id=id)
    old_dislike_value = old_dislike.dislike
    new_dislike = int(old_dislike_value) + 1
    Rating.objects.filter(book_id=id).update(dislike=new_dislike)

    return HttpResponse(json.dumps(str(new_dislike)))

        #
#
# def create_cat(request):
#     # return HttpResponse("Hello, world!")
#     if request.method == "POST":
#         Category.objects.create(title=request.POST['title'], description=request.POST['description'])
#     cat = Category.objects.all()
#     return render(request, 'books/form_author.html', {'cats': cat})
#
#
# def info_book(request):
#     # book_info = Book.objects.get(pk=1)
#     # return render(request, 'books/books.html', {'book_info': book_info})
#     t = loader.get_template('books/info_books.html')
#     c = {'books': Book.objects.all().prefetch_related('authors')}
#     return HttpResponse(t.render(c, request))
#
#
# def category(request):
#     # return HttpResponse("Hello, world!")
#     categories = Category.objects.all()
#     return render(request, 'books/category.html',
#                   {'categories': categories})
#
#
# def authors(request):
#     # return HttpResponse("Hello, world!")
#     authors = Author.objects.all()
#     return render(request, 'books/authors.html',
#                   {'authors': authors})
#
#
# def books(request):
#     # return HttpResponse("Hello, world!")
#     books = Book.objects.all()
#     return render(request, 'books/books.html',
#                   {'books': books})

books/templates/books/author_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <!--<p>Are you sure you want to delete "{{ object }}"?</p>-->
        <p>Are you sure you want to delete "{{ object.name }}"?</p>


    <input type="submit" value="Confirm" />
</form>

books/templates/books/author_detail.html
        Name: {{ author.name }}<br>
        Date of Birth: {{ author.date_bir }}<br>
        Biography: {{ author.bio }}

books/templates/books/author_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method='POST' action="{% url 'author_create' %}">
    {% csrf_token %}
    {{form.as_p}}
  <!--<input type="text" name="title">title<br>-->
  <!--<input type="text" name="description">description<br>-->

  <p><input type="submit">OK</p>
 </form>
</body>
</html>

books/templates/books/author_update_form.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

books/templates/books/book_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <!--<p>Are you sure you want to delete "{{ object }}"?</p>-->
        <p>Are you sure you want to delete "{{ object.title }}"?</p>


    <input type="submit" value="Confirm" />
</form>

books/templates/books/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method='POST' action="{% url 'book_create' %}">
    {% csrf_token %}
    {{form.as_p}}
  <!--<input type="text" name="title">title<br>-->
  <!--<input type="text" name="description">description<br>-->

  <p><input type="submit">OK</p>
 </form>
</body>
</html>

books/templates/books/book_update_form.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

books/templates/books/books_list.html
{% extends 'books/index.html' %}

{% block content %}
    <h1>All Books</h1>
        <a href="/books/book_create/">Create</a>
<br><br>
    {% for book in all_books %}
        {{ book.title }}
               <div>{% for r in book.rating_set.all %}
                   <div >
                   <button class='like' style="float: left;" value={{ book.id }} >+</button>
                       <div style="float: left;" class="l">{{ r.like }}</div>
                   <button class='dislike' style="float: left;" value={{ book.id }}>-</button>
                       <div style="float: left;" class="dl">{{ r.dislike }}</div>
                   </div>
        {% endfor %}
        </div>
        <br>

        <a href="/books/detail_book/{{ book.pk }}">detail</a>
        <a href="/books/book_update/{{ book.pk }}">update</a>
        <a href="/books/book_delete/{{ book.pk }}">delete</a>
        <br>

        --------------------------------------------------------
        <br>
    {% endfor %}
{% endblock %}

books/templates/books/category_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <!--<p>Are you sure you want to delete "{{ object }}"?</p>-->
        <p>Are you sure you want to delete "{{ object.title }}"?</p>


    <input type="submit" value="Confirm" />
</form>

books/templates/books/category_detail.html
 Title: {{ cat.title }}<br>
        description: {{ cat.description }}

books/templates/books/category_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method='POST' action="{% url 'category_create' %}">
    {% csrf_token %}
    {{form.as_p}}
  <!--<input type="text" name="title">title<br>-->
  <!--<input type="text" name="description">description<br>-->

  <p><input type="submit">OK</p>
 </form>
</body>
</html>

books/templates/books/category_list.html
{% extends 'books/index.html' %}

{% block content %}

    <h1>All categories</h1>
        <a href="/books/category_create/">Create</a>
<br><br>
    {% for cat in categories %}
        id: {{ cat.pk }}<br>
        Title: {{ cat.title }}<br>
        description: {{ cat.description }}<br>
        <a href="/books/category_update/{{ cat.pk }}">update</a>
        <a href="/books/category_delete/{{ cat.pk }}">delete</a>
        <br>
        --------------------------------------------------------
        <br>

    {% endfor %}
    <br>
{% endblock %}

books/templates/books/comment_form.html
{% extends 'books/book_detail.html' %}

{% block new_comment %}
   <form method='POST' action="{% url 'comment_create' %}">
    {% csrf_token %}
    {{form.as_p}}
  <!--<input type="text" name="title">title<br>-->
  <!--<input type="text" name="description">description<br>-->

  <p><input type="submit">OK</p>
 </form>
{% endblock %}

books/templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    {% csrf_token %}
    <meta charset="UTF-8">
    <title>Title</title>
            <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'books/css/style.css' %}">
    <script src="{% static 'books/js/main.js' %}"></script>

</head>
<body>

        {% if user.is_authenticated %}
        <h3>hello, {{ user.username }}!</h3>
        {% else %}
        <h3>hello, user!</h3>
        {% endif %}

        {% if user.is_authenticated %}
        <a href="/my_auth/logout/">Logout</a><br />
        {% else %}
        <a href="{% url 'my_auth:login_view' %}" >Sign In</a>
        <a href="{% url 'my_auth:register_view' %}">Sign Up</a><br />
        {% endif %}




<div>
    <a href="/books/all_books/">Books</a>
    <a href="/books/authors/">Authors</a>
    <a href="/books/categories/">Category</a>
</div>

{% block content %}
{% endblock %}
</body>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

</html>